# Generated by Django 5.0.4 on 2024-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsnapp', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='show_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_on_site',
            field=models.BooleanField(default=False),
        ),
    ]
